### PR TITLE
Just some suggestions

### PR DESCRIPTION
**Pull request by treenerd**
I'll suggest to use an own recipe to add the repository.
Also fore more flexability when using wrapper cookbooks I would like to have dependencies in the role run_list.
I only tested CentOS 7.0 support. I did the changes in the notifies to "restart" because "reload" was not supported.
Also I used "delayed" to reduce restarts.

### CODE REVIEW

**Comment by sitle** [comment]
@treenerd I pretty much agree with all your PR except the 0212899 but let's ask @GitBytes what he thinks about that. If it's ok with him, i'll merge your PR.

Thank you very much for your work.

**Comment by GitBytes** [comment]
@sitle @treenerd Hey Guys! To start, I do like where you are going with splitting out the repo bits, that is a very common practice and that should probably be done. However, I have a couple of issues with other bits.

Although I completely agree with restarting the file and storage daemons, I am not sure that logic should carry through to the director daemon. My reason for this is, if one little change is made and you have a large queue of running jobs on a production system, you will inevitably kill jobs, which can easily be undesirable. I am speaking to commit https://github.com/treenerd/chef-bareos/commit/64bff0ae87f32c1e201b0ac9d7afa7869d9922ee in this case.

So, in terms of moving the repo bits, please continue on that path, I would just say pull that new recipe back into the default recipe with an `include_recipe 'chef-bareos::repo'` bit so anyone can include just the default recipe and get them partially "there" initially. I believe this would be included in commit https://github.com/treenerd/chef-bareos/commit/f56d868c277d04cf9294bdda8d2c8d6369e9965c.

I am totally happy with adding https://github.com/treenerd/chef-bareos/commit/172b24edd88d7a7f8ef0b98641935f8c73332b0f.

I am good with commit https://github.com/treenerd/chef-bareos/commit/e4f013656ae6ced78b3ed99c75b22884fce3cb37 with the caveat of my point regarding including the repo recipe in the default recipe. On a slight additional note, I also recommend this so users do not have to include additional recipes in the role unless they wish to for some reason, thereby cutting out the password OpenSSL cookbook bits we have in there as well.

With commit https://github.com/treenerd/chef-bareos/commit/0212899ed3f7f7e440f7dac578ad665a3b3c758e refer to previous comments.  =)

Please feel free to comment and discuss, I am open to suggestions. Thanks for the help!

Best Regards,
Gitbytes (Ian)

**Comment by treenerd** [comment]
@GitBytes @sitle 

First of all thank you for your fast response!

treenerd@64bff0a  You are totally right, I already use bareos in production, but without chef at the moment. I'll setup a small testsystem and try what ist the best solution to avoid killing the jobs. In my mind it shouldn't be that problem to restart the director, because it won't stop the transmission between storage and client. But I always installed this on different nodes.

treenerd@f56d868 I understand you and with the logic in the roles that we use in the test roles you are totaly right; Normally I would like to include all recipes in the run_lists so it's easier to use the cookbook on different installations with wrapper cookbooks an own roles.

 treenerd@172b24e :-D that was easy;

And a question at the end; It was a bit late in the morning when I've done the commit, and after that I recognized there is a development branch. So is it better for you when I add my suggestions in the development branch? Or should I made pull requests in the master?

**Comment by GitBytes** [comment]
@treenerd Yeah, no problem! I actually had the same thing come up for my work when I started submitting PRs for the cookbook. If it is easier for you to commit to master that would probably be ok but we just need to make sure to look things over more closely before we can merge. If you want to use the develop branch, we can work through issues slightly cleaner versus master. I have started doing this myself and hope to add more features and some more reworked bits that I hope to merge back to master at some point soon. Don't worry about it in this case but going forward that option is definitely available to you.

Feel free to setup an installation to test the scenario you are considering and let me know how it plays out. Afterwards, make any additional alterations to your PR to address the results and resubmit for a TravisCI test. Then I can look it over again and see if we are closer to an agreed upon alteration to master? Thanks sir!

@sitle Any other feedback on this is awesome, if none I can work with him and get a solution in place. This is ultimately your cookbook so if you want to keep the repos in the default recipe we can work that out as well just keep us posted. Thanks in advance! =)

BR, GitBytes (Ian)

**Comment by treenerd** [comment]
@GitBytes 

Yes sure I'll try to work that out, even with the reload stuff;

@sitle 

I think it's just a suggestion, so for me it's no problem if you decide to include the repo in the default recipe.

**Comment by GitBytes** [comment]
@treenerd 

Awesome!

Again, I think just the director is the daemon to consider for reload versus restart. Looking forward to the results.

I had another thought/question.. Why did you want to take out the `include_recipe 'chef-bareos::client'` line in the default recipe? Sorry, been a really long day, I may be losing it at this point and need some sleep.. =P I think you said for wrapper or role reasons? Sorry just looking for additional clarification. Thanks again!

**Comment by sitle** [comment]
@GitBytes @treenerd It makes sense for me that the default recipe install and configure the client parts.  We can change that way, I just need some more clarification because it affects all operating system (Debian like for me). I don't use Redhat like system often, so I don't think I can help well with questions around that OS (but I will help for sure if you need my opinion of course :)).

Thanks guys.

**Comment by treenerd** [comment]
@sitle @GitBytes

You know there are cases where I don't need a File deamon on a storage node, Because I have multiple Datacenter with more than one storage node. And when I roll out this ohysical vm or even a vm with chef i don't need the bareos-fd installed. just an example.

An other thing that I would like to implement is a config test before the reload. So it can never happen that ther will be roled out an failing configuration. An other thing would be to just install bconsole on an service node in a Datacenter, on such a node I also don't need a file-deamon.

Thats just why I tried to remove the client recipe from the default recipe. It's not a big issue for me, because I could deactivate the fd with a wrapper cookbook.

And why I use wrapper cookbooks? It's easier to maintenance the external cookbooks then. just update and thest if everything is working. So for me I always try to create some kind of "application cookbook" which is very generic and is doing the basic stuff like installation and just basic configuration. With the wrapper cookbook I add then more environment specific configurations. or change the default attributes. therefore I would suggest also to use LWRP's that we can use in the wrapper cookbooks again. Or in other cookbooks, for example if you want to backup from an recipe which is installing apache websites, you could also use the lwrp cookbook to add special configurations in the file-deamon. But I also have to think more about that stuff.

Have a nice day, cya

**Comment by GitBytes** [comment]
@treenerd all good on the wrapper cookbook bit. And I see your point on taking out the client recipe from the default recipe. That helped actually. Go ahead and get the PR updated whenever you have time with things we have talked about and we should probably be ok to merge. @sitle I will make sure your Ubuntu bits don't break before we get a new version to the supermarket regardless of the merge that happens here. Thanks all.

**Comment by sitle** [comment]
@treenerd It makes sense, thank you very much for your patience. Let's do it that way.

@GitBytes @treenerd 

I prefer to use the dev branch for PR then merge to master when we release a new version if it's ok with you. We can make the dev branch, the default one if it's more convenient for you. Thanks all.

**Comment by treenerd** [comment]
@sitle 
Yes sure; I think thats a good idea to put that stuff into the dev branch! Would be the best solution;
I'll make a new PR in the dev branch if that is okay for you.

Thanks

**Pull request closed without merging**
