### PR TITLE
Updating several aspects of Cookbook

### PR DESCRIPTION
**Pull request by GitBytes**
- Updating Cookbook to use ChefDK >0.6.0
- Updating Docs
- Updating Postgresql Logic/Commands
- Updating a couple of template bits for the director
  - Adding new attributes, working on more for future implementation
- Updating Kitchen suites/platforms/provisioner
  - Adding some test roles for tests
- Updating chefspec/rspec/serverspec testing
- Updating TravisCI testing parameters so they are more standard

Please review and let me know if you would like me to rework something. I am planning to make some more changes in the coming days. Thanks!  Best Regards, Gitbytes (Ian)

### CODE REVIEW

**Comment by GitBytes** [comment]
I am also renaming the cookbook technically within the metadata file. This was to keep consistent throughout the rest of the cookbook process. Please let me know your thoughts on this. In my humble opinion, we should either have the cookbook named bareos or chef-bareos, not both. Thanks again.

**Comment by sitle** [comment]
@GitBytes First of all, thank you for your work. I'm ok to change the name for chef-bareos.

**Comment by GitBytes** [comment]
@sitle Thank you very much for taking a look at my changes! I am glad they were to your liking. I look forward to working with you on this cookbook! :)  As I do not currently have permission to update the Supermarket available version of this cookbook, would you have time to handle this aspect as well if you haven't already? Thanks in advance!  Best Regards, GitBytes (Ian)

**Comment by sitle** [comment]
@GitBytes The supermarket is up to date as agreed with the new cookbook 's name.

**Comment by GitBytes** [comment]
@sitle Thank you for fixing that. Have a great day!

**Pull request merged**
